version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - ./dockercompose/redis/data:/data
      - ./dockercompose/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    command: redis-server --requirepass sta_go --appendonly yes

  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    container_name: mysql
    volumes:
      - ./dockercompose/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: sta_go
    restart: always
